name: build-client
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: duosecurity/duo_client_java
          path: duo_client_java
          ref: 0.5.0
      - run: ls -al .

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: cd duo_client_java &&mvn --file pom.xml -DskipTests
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging


      

