- name: Checkout
  uses: actions/checkout@v3
  with:
    path: main

- name: Checkout tools repo
  uses: actions/checkout@v3
  with:
    repository: duosecurity/duo_client_java
    path: duo_client_java
    ref: 0.5.0

